### ISSUE TITLE
Question about the delta used for spectral analysis SpectralTrainFig run spectral

### ISSUE THREAD

**Issue by JLArnold** [nsrr/spectraltrainfig-documentation#2]
https://www.sleepdata.org/tools/spectraltrainfig/pages/run-spectral.md

I have never used spectral analysis for EEGs and have question about the band used for delta.
Delta waves in general are <4 Hz, but the delta range for scoring deep sleep is 0.5-2 Hz with amplitude >75 microVolts. Does this analysis take the amplitude of the wave as part of the criteria? Below is screen shot of the spectral bands from this page and screen shot to show definition of delta for stage 3 from the AASM 2007 scoring manual.
![image](https://cloud.githubusercontent.com/assets/16805718/12495026/53cbdb98-c05b-11e5-97a6-684534814a90.png)
![image](https://cloud.githubusercontent.com/assets/16805718/12495031/5a101f5a-c05b-11e5-8dec-1df312cbb99f.png)

**Comment by mmorrical** [comment]
Currently spectraltrainfig only uses frequency for defining these waveforms.  This is one of several reasons the hand-scored hypnogram is used for verifying results to differentiate between sections of slow wave meeting stage 3 criteria, intermittent slow wave activity (<20% of epoch) and artifact (sweat, popping, etc).
Several groups using spectral data are concerned with all slow activity, whether or not it meets AASM criteria for either amplitude or % of epoch.
