### ISSUE TITLE
Missing period section error due to EOT or STX item (2) SpectralTrainFig Spectral Trouble

### ISSUE THREAD

**Issue by JLArnold** [nsrr/spectraltrainfig-documentation#3]
https://www.sleepdata.org/tools/spectraltrainfig/pages/spectral-trouble.md
Missing period at end of sentence in this section under error due to EOT or STX, item [2] line 3 first sentence ends with word “message” then the next two words are “For example,”  maybe there is a missing period.
![image](https://cloud.githubusercontent.com/assets/16805718/12495417/91259e3c-c05d-11e5-85de-5f4ddc11d8c1.png)

**Comment by mrueschman** [comment]
Closed in 8ca2612c433ee4150bda6a71960552f009eb3d86
